apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scc-reader-writer
rules:
- apiGroups:
  - security.openshift.io
  resources: 
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch  
