apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: build-robot
    namespace: myproject
roleRef:
  kind: ClusterRole
  name: scc-reader-writer
  apiGroup: rbac.authorization.k8s.io
