kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-test2
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges:
    - max: 6000
      min: 1000
